<?php

declare(strict_types=1);

/**
 * @file
 * Provides an about myself entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function about_myself_entity_theme(): array {
  return [
    'about_myself_entity' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for about myself entity templates.
 *
 * Default template: about-myself-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the about myself entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_about_myself_entity(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function about_myself_entity_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish about myself entities.
      $storage = \Drupal::entityTypeManager()->getStorage('about_myself_entity');
      $about_myself_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($about_myself_entity_ids) as $about_myself_entity) {
        $about_myself_entity->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize about myself entities.
      $storage = \Drupal::entityTypeManager()->getStorage('about_myself_entity');
      $about_myself_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($about_myself_entity_ids) as $about_myself_entity) {
        $about_myself_entity->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function about_myself_entity_user_predelete(UserInterface $account): void {
  // Delete about myself entities that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('about_myself_entity');
  $about_myself_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($about_myself_entity_ids)
  );
  // Delete old revisions.
  $about_myself_entity_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($about_myself_entity_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
